// Logo files generated by `npm run brand` from brand/source/.
import logoOnDark from '../../public/brand/logo-on-dark.png'
import logoOnLight from '../../public/brand/logo-on-light.png'

export { logoOnDark, logoOnLight }

export const BRAND = {
  name: "Irie's Cuisine",
  midnight: '#0c1c14',
  gold: '#ffd35b',
  forest: '#1b4e22',
  cream: '#fdf6e3',
}
